name: Deploy to GitHub Pages

# Run workflow on push to master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the latest code from the master branch
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure the full history is fetched

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify Node.js version if needed

      # Install dependencies and build the project
      - name: Install dependencies
        run: |
          npm install
          npm run build  # Adjust this if using a different build command

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "Suyash2711"
          git config --global user.email "suyashnigam34@gmail.com"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the correct GitHub token
          publish_dir: ./build  # Ensure this matches your build directory
